version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: estudiantes-db

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

    ports:
      - "${DB_PORT}:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer-angular

    ports:
      - "8081:8080"

    depends_on:
      - mysql

  backend:
    build: .

    container_name: angular-backend

    depends_on:
      - mysql

    ports:
      - "${BACK_PORT}:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/estudiantes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      BACK_PORT: ${BACK_PORT}

    restart: unless-stopped

volumes:
  mysql_data: