services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db-a

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

    ports:
      - "${DB_PORT}:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer-angular

    ports:
      - "8081:8080"

    depends_on:
      mysql:
        condition: service_healthy

  backend:
    build: .

    container_name: spring-angular-backend

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "${BACK_PORT}:${BACK_PORT}"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      BACK_PORT: ${BACK_PORT}

    restart: unless-stopped

volumes:
  mysql_data: