spring.application.name=backend
spring.docker.compose.enabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/estudiantes}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:piskero1989*}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect